version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
    - cadastrotarefas_cadastrotarefas_network

networks:
  cadastrotarefas_cadastrotarefas_network:
    external: true